---
# tasks file for install-mysql

- name: Install MySql
  yum:
    name: mysql-server
    state: present


- name: Install Mysql python
  yum:
    name: MySQL-python
    state: present


- name: Start MySql
  service:
    name: mysqld
    state: started
    enabled: true  
