---
# tasks file for create-user

- name: Create MySql user
  mysql_user:
    name: {{ mysql_user }}
    password: {{ mysql_password }}
    priv: *.*:ALL,GRANT
    login_user: {{ mysql_root_user }}
    login_password: {{ mysql_root_password }}
